export const ADD_MORE = 'Add More'
export const ADD_PRODUCTS = 'Add Products'
export const PRODUCT = 'Products'
export const ENTERT_TITLE='Enter Title'
export const CHOOSE_CATEGORY = 'Choose Category'
export const CHOOSE_SUB_CATEGORY = 'Choose Sub Category'
export const ENTER_PRICE = 'Enter Price'
export const UPLOAD_IMAGE = 'Upload Images'
export const PER_KG = 'per kg'
export const PUBLISH_NOW = 'Publish Now'
export const CANCEL = 'Cancel'
export const ENTER_DESCRPTION = 'Enter Descrption';
export const TERMS_AND_CONDITIONS ='Terms & Conditions';
export const BLACK = "#000000";
export const DARK_RED = "#5C2221";
export const LIGHT_GREY = "#F8F4F4";
export const MID_PEACH = "#8D7D75";
export const PRIMARY = "#A0272A";
export const TERTIERY = "#B7DEEC";
export const WHITE = "#FFFFFF";
export const deepLinkingURL='https://ruebensftcapp.page.link/63fF'