export const SEARCH = require("../assets/search.png");
export const EXPLORE_BTN = require("../assets/exploreBtn.png");
export const CHICKEN = require("../assets/chicken.png");
export const PORK = require("../assets/pork.png");
export const MEAT_IMAGE1 = require("../assets/meatimage1.jpg");
export const MEAT_IMAGE2 = require("../assets/meatimage3.jpg");
export const MEAT_IMAGE3 = require("../assets/meatimage3.jpg");
export const CART = require("../assets/cart.png");
export const badge = require("../assets/batge.png");
export const RATING = require("../assets/rating.png");
export const homeBackground = require("../assets/homeBackground.png");
export const splashScreenImage = require("../assets/applogo.png");
export const sampleProfile = require("../assets/sampleProfile.png");
export const shareIcon = require("../assets/shareIcon.png");
export const blogpostimage = require("../assets/blogpostimage.png");
export const home_unmarked = require("../assets/home_unmarked.png");
export const home_marked = require("../assets/home_marked.png");
export const element_unmarked = require("../assets/element_unmarked.png");
export const beef_image = require("../assets/beef.png");
export const lamp_image = require("../assets/lamp.png");
export const honey_image = require("../assets/honey.png");
export const element_marked = require("../assets/element_marked.png");
export const settings_unmarked = require("../assets/settings_unmarked.png");
export const settings_marked = require("../assets/setting_marked.png");
export const shop_unmarked = require("../assets/shop_unmarked.png");
export const shop_marked = require("../assets/shop_marked.png");
export const profile_marked = require("../assets/profile-marked.png");
export const profile_unmarked = require("../assets/profile_unmarked.png");
export const profile_pic = require("../assets/profile.png");
export const profileSample = require("../assets/profile_sample_test.jpg");
export const whatsapp = require("../assets/whatsapp.png");
export const phone = require("../assets/phone.png");
export const facebook = require("../assets/facebook.png");
export const instagram = require("../assets/instagram.png");
export const mail = require("../assets/mail.png");
export const backArrow = require("../assets/backArrow.png");
export const edit = require("../assets/edit.png");
export const Bill = require("../assets/bill.png");
export const APP_BACKGROUND = "#FFFFFF";
export const playIcon = require("../assets/playIcon.png");
export const BLACK = "#000000";
export const DARK_RED = "#5C2221";
export const LIGHT_GREY = "#F8F4F4";
export const MID_PEACH = "#8D7D75";
export const PRIMARY = "#A0272A";
export const TERTIERY = "#B7DEEC";
export const WHITE = "#FFFFFF";
export const PRIMARY_COLOR ='#A9C9F7'
export const SECONDARY_COLOR ='#BEDTTTI'
export const TEXT_COLOR ='#231F20'
export const SECONDARY_TEXT_COLOR ='gray'
export const BUTTON_TEXT_COLOR_PRIMARY ='white'
export const BUTTON_TEXT_COLOR_SECONDARY ='#231F20'
export const BUTTON_COLOR_PRIMARY ='#A9C9F7'
export const BUTTON_COLOR_SECONDARY ='#FFFFFF'

export const close = require("../assets/close1.png");
export const remove = require('../assets/remove.png');
export const plus = require('../assets/plus.png');
export const cow = require('../assets/cow.png');
export const arrowLeft = require('../assets/arrow_left.png');
export const pause = require('../assets/pause.png');
export const replay = require('../assets/replay.png');
export const backGroundImage = require("../assets/licensed-image.jpg");
export const downArrow = require('../assets/down-arrow.png');
export const minus = require('../assets/minus.png');
export const upArrow = require('../assets/up-arrow.png');
